### PR TITLE
feat: callconv, enum lits, inline assembly, whitespace fixes

### PR DESCRIPTION
**Pull request by sno2**
Something is still wrong with the enum literal lexing. I don't understand why, but a single `.` is stated as valid. However, the RegEx requires at least one character.

### CODE REVIEW

**Comment by sno2** [comment]
idk if you have already implemented some of this so you could really just copy it if you don't need it all. just playing around, really

**Comment by SuperAuguste** [comment]
This is awesome! Inline asm is especially annoying so tysm for taking that on! Is this mergeable or are you still adding more syntax? :)

**Comment by sno2** [comment]
I don't have any more changes atm. Sorry about the conflicts, I will have time to resolve them tomorrow night, but you can merge it if you would like to.

**Comment by SuperAuguste** [comment]
Thank you so much!

**Pull request merged**
